[2023-12-22T04:09:02.884+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v0222.create_postgres_table scheduled__2023-12-18T00:00:00+00:00 [queued]>
[2023-12-22T04:09:02.963+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v0222.create_postgres_table scheduled__2023-12-18T00:00:00+00:00 [queued]>
[2023-12-22T04:09:02.965+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2023-12-22T04:09:03.141+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-12-18 00:00:00+00:00
[2023-12-22T04:09:03.169+0000] {standard_task_runner.py:60} INFO - Started process 10486 to run task
[2023-12-22T04:09:03.214+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v0222', 'create_postgres_table', 'scheduled__2023-12-18T00:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp_qpv10fm']
[2023-12-22T04:09:03.256+0000] {standard_task_runner.py:88} INFO - Job 161: Subtask create_postgres_table
[2023-12-22T04:09:03.570+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_postgres_operator_v0222.create_postgres_table scheduled__2023-12-18T00:00:00+00:00 [running]> on host dd88aaafc1d9
[2023-12-22T04:09:04.143+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarwar' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v0222' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-18T00:00:00+00:00'
[2023-12-22T04:09:04.147+0000] {sql.py:276} INFO - Executing: 
        create table if not exists dag_runs (
        dt datetime,
        dag_id varchar,
        primary key(dt, dag_id)
        )
        
[2023-12-22T04:09:04.178+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-22T04:09:04.239+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-22T04:09:04.262+0000] {sql.py:432} INFO - Running statement: 
        create table if not exists dag_runs (
        dt datetime,
        dag_id varchar,
        primary key(dt, dag_id)
        )
        , parameters: None
[2023-12-22T04:09:04.279+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 437, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedObject: type "datetime" does not exist
LINE 3:         dt datetime,
                   ^

[2023-12-22T04:09:04.336+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag_with_postgres_operator_v0222, task_id=create_postgres_table, execution_date=20231218T000000, start_date=20231222T040902, end_date=20231222T040904
[2023-12-22T04:09:04.427+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 161 for task create_postgres_table (type "datetime" does not exist
LINE 3:         dt datetime,
                   ^
; 10486)
[2023-12-22T04:09:04.563+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-22T04:09:04.881+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
